// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzb4OMgl0KYsC42qfFlb61Xjlh3PFhcLo',
    appId: '1:304256998018:web:7718503ecef30e68eab29b',
    messagingSenderId: '304256998018',
    projectId: 'rehuddle',
    authDomain: 'rehuddle.firebaseapp.com',
    storageBucket: 'rehuddle.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5sb1HBpHsiMVZwo6Bb29d2tPnFpVorKM',
    appId: '1:304256998018:android:6ffcd85685c239edeab29b',
    messagingSenderId: '304256998018',
    projectId: 'rehuddle',
    storageBucket: 'rehuddle.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHu-gF68ZnBZIODk_oDPhFqjszAifvoAU',
    appId: '1:304256998018:ios:b75931126a6000edeab29b',
    messagingSenderId: '304256998018',
    projectId: 'rehuddle',
    storageBucket: 'rehuddle.firebasestorage.app',
    iosBundleId: 'com.example.rehuddle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHu-gF68ZnBZIODk_oDPhFqjszAifvoAU',
    appId: '1:304256998018:ios:b75931126a6000edeab29b',
    messagingSenderId: '304256998018',
    projectId: 'rehuddle',
    storageBucket: 'rehuddle.firebasestorage.app',
    iosBundleId: 'com.example.rehuddle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzb4OMgl0KYsC42qfFlb61Xjlh3PFhcLo',
    appId: '1:304256998018:web:a8236a47a6d597c7eab29b',
    messagingSenderId: '304256998018',
    projectId: 'rehuddle',
    authDomain: 'rehuddle.firebaseapp.com',
    storageBucket: 'rehuddle.firebasestorage.app',
  );

}